name: Compilar i pujar PDFs a Release

on:
  release:
    types: [published]

jobs:
  compile-and-upload:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }} 
      
      - name: Setup Typst
        uses: typst-community/setup-typst@v5
        with:
          typst-version: ^0.14.2
      
      - name: Compilar PDFs
        run: |
          mkdir -p build
          for subject in fisica matematiques quimica; do
            typst compile --root . ./resums/$subject/main.typ ./build/$subject.pdf
          done
      
      - name: Pujar PDFs al release actual
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.pdf
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}